### PR TITLE
Two minor improvements

### PR DESCRIPTION
**Pull request by elibarzilay**
Mostly makes things more readable.

### CODE REVIEW

**Comment by elibarzilay** [comment]
Normally I very much agree with this -- but the case here is that the `closer.next` line is part of the loop logic which is wrapped around a long piece of code -- and of course, it's clearer when code that deals with a single thing is localized.  In fact, when I read the code I missed one of those bits completely, and wondered how come it works with just the single one that I did see...  I would usually not do anything about it, but it seems to me like this is likely to be a popular place to look for a reference implementation (which is just what I did today), and therefore readability seems more important.

(As a sidenote, this is not something that I came up with -- I first saw that in a talk N years ago, which was surprising in that it seemed trivial: the main point was changing code like

    if (something) {
      main meat of the code
    } else {
      error("...")
    }

in the same way, therefore moving sanity checks, errors, etc to the top.  I didn't think much of it at the time, but later on I experimented with it and saw how much it improves readability.  I expected to dislike an extra negation (in some cases there is a negation in the first form, but usually not), but then I saw that the advantage is bigger than the disadvantage.  "If this, blah blah blah, then blah, and another blah. Else error." vs "If not this, error, else blah blah blah, then blah, and another blah.")

In any case, the other commit is independent of this.

**Comment by jgm** [comment]
@elibarzilay I understand the motivation, and I think I agree, on looking at the code again, that it's more readable your way.

**Comment by elibarzilay** [comment]
Thanks -- I've seen a few more of these, but avoided commenting since I don't to become a preacher...  (But if you want, I'll report them when/if I run into them...)

**Comment by jgm** [comment]
+++ Eli Barzilay [Apr 29 15 03:37 ]:
>Thanks -- I've seen a few more of these, but avoided commenting since I don't to become a preacher...  (But if you want, I'll report them when/if I run into them...)

Sure.

**Pull request merged**
